### ISSUE TITLE
Use gitlab CI to build binaries

### ISSUE THREAD

**Issue by bmanojlovic** [sinokylin/terraform-provider-ovirt#34]
already prepared .gitlab-ci.yml can be found at
https://github.com/bmanojlovic/terraform-provider-ovirt/blob/master/.gitlab-ci.yml
and its output at:
https://gitlab.com/bmanojlovic/terraform-provider-ovirt/pipelines

gitlab.com allows for repository mirroring which i have used in this case for my forked repository and it should build on any repository update on [github](https://github.com)

for any info regarding used variables see: https://docs.gitlab.com/ee/ci/variables/

Before pushing mine change into your repository i would like to discuss if  it is fine with you to have this file or not

**Comment by imjoey** [comment]
hi, great thanks for new CI option. While [Travis CI](https://travis-ci.org) seems like an more famous CI tool in Github world. I've used it in [ovirt-engine-sdk-go](
https://github.com/imjoey/ovirt-engine-sdk-go/blob/master/.travis.yml) to automatically build and generate the go-sdk code followed by push [back](https://github.com/imjoey/go-ovirt). This is also adopted by [Official Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.travis.yml). 
Hope for your feedbacks.

**Comment by bmanojlovic** [comment]
sure travis ci is ok too, just i use gitlab "in house" so for me it is "nicer".
Anyway will try to use travis CI.
